# Generated by Django 3.1.1 on 2022-07-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to='')),
                ('Eventname', models.CharField(max_length=255)),
                ('Hostname', models.CharField(max_length=255)),
                ('Date', models.DateField()),
            ],
            options={
                'verbose_name': 'Events_Data',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to='')),
                ('Eventname', models.CharField(max_length=255)),
                ('Hostname', models.CharField(max_length=255)),
                ('Date', models.DateField()),
            ],
            options={
                'verbose_name': 'Programs_Register',
            },
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('Firstname', models.CharField(max_length=255)),
                ('Lastname', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=255)),
                ('Createdon', models.DateField(auto_now_add=True)),
                ('Desc', models.TextField()),
                ('Intrests', models.CharField(max_length=255)),
                ('Timeline', models.TextField()),
            ],
            options={
                'verbose_name': 'USER_DETAILS',
            },
        ),
    ]
